import {GenealogyBee,beeLabel} from './GenealogyBee.jsx';
import React,{useState} from 'react';
import {Navigation,PageJourney,PageHeadingLabel} from './Navigation.jsx';
import {formulaAncestry,editableAncestors} from './ancestralScenarios.js';
import {fibonacciLevels} from './model.js';
export default function AncestralScenarioPage(){
 const [active,setActive]=useState([...editableAncestors]),[g,setG]=useState(2);
 const tree=formulaAncestry(active),fib=fibonacciLevels(6),N=tree.counts,D=tree.diploidCounts;
 const toggle=path=>setActive(prev=>prev.includes(path)?prev.filter(p=>p!==path):[...prev,path]);
 return <main className="scenario-page"><header><Navigation page="scenarios"/></header>
 <section className="colony-intro"><PageHeadingLabel page="scenarios"/><h1>Un padre in più.<br/><em>Cosa cambia?</em></h1><p>Risaliamo agli antenati di un maschio aploide. N(g) conta tutti gli individui del livello g; D(g) conta i maschi diploidi di quel livello.</p></section>
 <aside className="reading-note" aria-label="Da tenere a mente"><strong>Da tenere a mente</strong><p>Torniamo alla genealogia standard: che cosa cambia quando un maschio ha due genitori? Manteniamo gli antenati tutti distinti e ammettiamo che anche i maschi diploidi possano riprodursi. È un’ipotesi matematica: qui non seguiamo la trasmissione genetica.</p></aside>
 <section className="formula-focus"><h2>N(g + 1) = N(g) + N(g − 1) + D(g)</h2><p>Ogni individuo aggiunge una madre. Le femmine e i maschi diploidi aggiungono anche un padre.</p><div className="formula-check"><div className="stepper" aria-label="Generazione della verifica"><button onClick={()=>setG(g-1)} disabled={g===1} aria-label="Verifica la generazione precedente">−</button><span>g = <strong>{g}</strong></span><button onClick={()=>setG(g+1)} disabled={g===5} aria-label="Verifica la generazione successiva">+</button></div><div className="formula-numbers" role="status"><span><strong>{N[g+1]}</strong><small>N({g+1})</small></span><b>=</b><span><strong>{N[g]}</strong><small>N({g})</small></span><b>+</b><span><strong>{N[g-1]}</strong><small>N({g-1})</small></span><b>+</b><span className="diploid-term"><strong>{D[g]}</strong><small>D({g})</small></span></div></div></section>
 <section className="lab"><div className="lab-heading"><div><p className="eyebrow">L’ALBERO DEGLI ANTENATI</p><h2>Modifica la ploidia dei tre nodi evidenziati</h2></div></div><p className="scenario-result">Clicca un nodo con il bordo marcato per alternare <strong>M·n ↔ M·2n</strong>. Il maschio aploide ha solo una madre; quello diploide ha anche un padre. Il grafo si ricostruisce secondo la nuova ipotesi.</p>
 <div className="scenario-table-wrap"><table className="scenario-table"><caption>Conteggi generati dalle regole di parentela</caption><thead><tr><th scope="col">Livello</th>{fib.map((_,i)=><th key={i} scope="col">gen.{i}</th>)}</tr></thead><tbody><tr><th scope="row">Individui N(g)</th>{N.map((n,i)=><td key={i} className={n!==fib[i]?'different':''}>{n}</td>)}</tr><tr><th scope="row">Maschi diploidi D(g)</th>{D.map((n,i)=><td key={i}>{n}</td>)}</tr><tr><th scope="row">Fibonacci</th>{fib.map((n,i)=><td key={i}>{n}</td>)}</tr></tbody></table></div>
 <p className="scenario-result">{active.length===0?'Tutti i maschi sono aploidi: 1, 1, 2, 3, 5, 8, 13. La ricorrenza si riduce a Fibonacci.':`${active.length} maschi diploidi. Il loro contributo diretto compare nel livello dei genitori; i rami aggiunti continuano nei livelli successivi.`}</p>
 <div className="graph-meta"><p>Verso gli antenati ↓</p><div className="legend">{[{type:'F',diploid:false,text:'F · femmina'},{type:'M',diploid:false,text:'M·n · maschio aploide'},{type:'M',diploid:true,text:'M·2n · maschio diploide'}].map(item=><span className="bee-legend-item" key={item.text}><svg width="34" height="34" viewBox="-18 -18 36 36" aria-hidden="true"><GenealogyBee type={item.type} diploid={item.diploid}/></svg>{item.text}</span>)}</div></div><div className="graph-scroll" tabIndex="0" role="region" aria-label="Albero interattivo degli antenati"><svg width={tree.width} height={tree.height} viewBox={`0 0 ${tree.width} ${tree.height}`} role="group" aria-label={`Conteggi: ${N.join(', ')}`}>
 {tree.levels.map((l,i)=><g key={i}><rect x="0" y={16+i*94} width={tree.width} height="65" fill={i===g?'#f0ecdb':i===g+1?'#f0f3ea':'transparent'}/><text x="20" y={42+i*94} className="generation">gen.{i}</text><text x="20" y={61+i*94} className="row-count">{l.length} {l.length===1?'individuo':'individui'}</text></g>)}
 {tree.nodes.flatMap(n=>n.parents.map(p=><path key={n.id+p.id} d={`M${n.x} ${65+n.g*94} C${n.x} ${91+n.g*94},${p.x} ${91+n.g*94},${p.x} ${24+p.g*94}`} fill="none" stroke={p.extra?'#bc833e':'#bdc9b4'} strokeWidth={p.extra?2:1.5}/>))}
 {tree.nodes.map(n=>n.editable?<foreignObject key={n.id} x={n.x-28} y={25+n.g*94} width="56" height="65"><button type="button" className={`ploidy-node bee-ploidy-node ${n.diploid?'diploid':''}`} aria-label={`Maschio in gen.${n.g}: ${n.diploid?'diploide, rendi aploide':'aploide, rendi diploide'}`} aria-pressed={n.diploid} onClick={()=>toggle(n.path)} title="Clicca per cambiare ploidia"><svg width="40" height="40" viewBox="-20 -20 40 40" aria-hidden="true"><GenealogyBee type="M" diploid={n.diploid}/></svg><span>{beeLabel(n.sex,n.diploid)}</span></button></foreignObject>:<g key={n.id}><title>{n.sex==='F'?'Femmina':'Maschio aploide'} · gen.{n.g}</title><GenealogyBee type={n.sex} diploid={n.diploid} x={n.x} y={45+n.g*94}/><text x={n.x} y={78+n.g*94} textAnchor="middle" className="node-label">{beeLabel(n.sex,n.diploid)}</text></g>)}

 </svg></div><div className="graph-footer"><span>Ocra: ramo aggiuntivo.</span><span>gen.6 è solo il limite della vista.</span></div></section>
 <section className="scenario-explanation"><div><h2>Da dove arriva N(g − 1)?</h2><p>Ogni individuo del livello g − 1 ha una madre distinta nel livello g. Le femmine del livello g sono quindi esattamente N(g − 1).</p><p>Per costruire g + 1 contiamo: N(g) madri, N(g − 1) padri delle femmine e D(g) padri dei maschi diploidi. Sommando otteniamo la formula, valida per g ≥ 1.</p></div><div><h2>Un effetto che si propaga</h2><p>Un diploide in gen.2 aggiunge un padre in gen.3. Anche se D(3) è zero, quel padre ha una madre e la differenza continua in gen.4. D(g) misura il contributo nuovo, non tutta la differenza da Fibonacci.</p><p>Le ipotesi sono: maschio aploide iniziale, femmine con due genitori, maschi aploidi con una madre, diploidi con due genitori e antenati sempre distinti. Ammettiamo la riproduzione dei diploidi come ipotesi matematica; non simuliamo la trasmissione genetica.</p></div></section>
 <section className="reading-conclusion"><h2>Che cosa abbiamo contato?</h2><p>Abbiamo contato individui distinti a ogni livello dell’albero, risalendo nel passato. Ogni maschio diploide introduce un padre aggiuntivo e il suo ramo ancestrale. Quando tutti i maschi sono aploidi, nelle ipotesi di questo albero ritroviamo Fibonacci.</p></section>
 <PageJourney page="scenarios"/></main>;
}
