import React,{useState} from 'react';
import {Navigation} from './Navigation.jsx';
import {csdCross} from './csd.js';
import {CsdInfo} from './CsdInfo.jsx';
import {DiploidInfo} from './DiploidInfo.jsx';
function Allele({value}){return <span className={`allele allele-${value}`}>{value}</span>}
export default function CsdPage(){
 const [shared,setShared]=useState(true),[selected,setSelected]=useState(0);
 const father=shared?'A':'C',outcomes=csdCross(['A','B'],father),child=outcomes[selected];
 return <main className="csd-page"><header><a href="#/" className="brand">✳ API MATEMATICHE</a><Navigation page="csd"/></header>
 <section className="intro"><p className="eyebrow">ESPERIMENTO 03 / ALLELI E SESSO</p><h1>Due genitori.<br/><em>Non sempre femmina.</em></h1><div className="csd-intro-copy">Un uovo fecondato riceve un <span className="term-info">allele <em>csd</em><CsdInfo/></span> da ciascun genitore.<br className="desktop"/> In questo modello, conta se le due versioni sono uguali o diverse.</div></section>
 <aside className="csd-key-point" aria-labelledby="csd-key-heading"><p className="eyebrow">IL PASSAGGIO DAL MODELLO FIBONACCI</p><h2 id="csd-key-heading">Maschio non significa sempre un solo genitore.</h2><p>La regola «ogni M ha soltanto una madre» della pagina Fibonacci si riferisce ai <strong>maschi aploidi</strong>. Qui introduciamo anche il <strong>maschio diploide nato da fecondazione</strong>, che ha una madre e un <span className="term-info">padre<DiploidInfo/></span>. Il sesso da solo non basta più a contare i genitori.</p></aside>
 <section className="event-control"><div><h2>Il padre condivide un allele con la madre?</h2><p>La madre ha sempre A/B. Il padre aploide ha A se condivide un allele, C se ne ha uno diverso. A, B e C rappresentano versioni funzionalmente distinte dello stesso gene.</p></div><label className="event-switch"><input type="checkbox" role="switch" checked={shared} onChange={e=>setShared(e.target.checked)}/><span>Allele condiviso</span><strong>{shared?'Sì · padre A':'No · padre C'}</strong></label></section>
 <p className="history-note">Studiamo soltanto le uova fecondate, prima di considerare sopravvivenza e selezione. Le percentuali sono probabilità teoriche per ogni uovo, non quantità garantite in una covata.</p>
 <section className="csd-parents" aria-label="Genitori dell’incrocio"><article><p className="eyebrow">MADRE / FEMMINA DIPLOIDE</p><div className="allele-pair"><Allele value="A"/><Allele value="B"/></div><h2>Due alleli, un solo contributo.</h2><p>Ogni uovo riceve A oppure B, ciascuno con probabilità ½.</p></article><span className="cross-sign" aria-hidden="true">×</span><article><p className="eyebrow">PADRE / MASCHIO APLOIDE</p><div className="allele-pair"><Allele value={father}/></div><h2>Un allele, sempre lo stesso.</h2><p>Ogni spermatozoo porta {father} al locus <em>csd</em> nel nostro modello, senza mutazioni.</p></article></section>
 <section className="lab csd-outcomes"><div className="comparison-heading"><p className="eyebrow">I DUE ESITI POSSIBILI</p><h2>Che cosa eredita il figlio?</h2><p>Seleziona un esito per vederne i genitori. I due riquadri rappresentano possibilità alternative per un singolo uovo.</p></div><div className="outcome-grid">{outcomes.map((o,i)=><button key={o.id} className={`outcome-card ${selected===i?'selected':''}`} aria-pressed={selected===i} onClick={()=>setSelected(i)}><span className="outcome-probability">50% · allele materno {o.alleles[0]}</span><span className="allele-pair"><Allele value={o.alleles[0]}/><span className="allele-plus">+</span><Allele value={o.alleles[1]}/></span><strong>{o.sex==='M'?'Maschio diploide':'Femmina diploide'}</strong><span>{o.sex==='M'?'A/A · omozigote: due alleli uguali':`${o.alleles.join('/')} · eterozigote: due alleli diversi`}</span></button>)}</div><p className="event-feedback" role="status">{shared?'Tra le uova fecondate: 50% maschi diploidi A/A e 50% femmine A/B. Non è necessaria una nuova mutazione: A è ereditato da entrambi i genitori.':'Tra le uova fecondate: 100% femmine diploidi, metà A/C e metà B/C. Il contributo paterno è diverso da entrambi i possibili contributi materni.'}</p></section>
 <section className="csd-pedigree lab"><div className="comparison-heading"><p className="eyebrow">SESSO E GENEALOGIA SONO PROPRIETÀ DISTINTE</p><h2>{child.sex==='M'?'Questo maschio diploide ha due genitori.':'Questa femmina diploide ha due genitori.'}</h2></div><div className="pedigree-content"><svg viewBox="0 0 540 260" role="img" aria-label={`${child.sex==='M'?'Maschio':'Femmina'} diploide ${child.alleles.join('/')} con madre A/B e padre ${father}`}><path d="M270 173 L145 88 M270 173 L395 88" fill="none" stroke="#bcc8ad" strokeWidth="2"/><rect x="55" y="18" width="180" height="76" rx="12" fill="#f6e4b6"/><text x="145" y="47" textAnchor="middle" className="pedigree-label">MADRE · F · 2n</text><text x="145" y="76" textAnchor="middle" className="pedigree-alleles">A/B</text><rect x="305" y="18" width="180" height="76" rx="12" fill="#dbe8e2"/><text x="395" y="47" textAnchor="middle" className="pedigree-label">PADRE · M · n</text><text x="395" y="76" textAnchor="middle" className="pedigree-alleles">{father}</text><rect x="160" y="168" width="220" height="78" rx="12" fill={child.sex==='M'?'#dbe8e2':'#f6e4b6'} stroke="#ac9760"/><text x="270" y="195" textAnchor="middle" className="pedigree-label">{child.sex==='M'?'MASCHIO':'FEMMINA'} · 2n</text><text x="270" y="227" textAnchor="middle" className="pedigree-alleles">{child.alleles.join('/')}</text></svg><div><p>L’esito selezionato è un <strong>{child.sex==='M'?'maschio':'individuo femminile'} diploide {child.alleles.join('/')}</strong>. È nato da fecondazione: i suoi genitori sono sempre due.</p><p className="history-note">n = una serie di cromosomi; 2n = due serie. Le lettere mostrano soltanto gli alleli di un locus, non l’intero corredo cromosomico.</p></div></div></section>
 <section className="event-lessons"><article><p className="eyebrow">LA REGOLA GENETICA</p><h2>Una copia, due copie.<br/>Uguali o diverse.</h2><p>Nel modello semplificato di determinazione complementare del sesso: una copia di <em>csd</em> in un individuo aploide dà un maschio; due copie uguali danno un maschio diploide; due copie funzionalmente diverse danno una femmina diploide.</p><p><strong>Omozigote</strong> significa avere due alleli uguali a quel locus. Non significa avere due «cromosomi mutati», né essere omozigote in tutti i geni.</p></article><article><p className="eyebrow">IL CONFINE DELL’ESPERIMENTO</p><h2>L’origine resta.<br/>Il destino è un’altra domanda.</h2><p>Nelle colonie di api mellifere, i maschi diploidi vengono normalmente eliminati dalle operaie nelle prime fasi larvali. Qui ci fermiamo alla determinazione del sesso: non simuliamo mortalità o riproduzione successiva.</p><p>Una morte successiva non cancellerebbe la madre e il padre. La sopravvivenza riguarda il destino dell’individuo, non la sua origine.</p><p className="source-note">Fonte: <a href="https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1000222" target="_blank" rel="noreferrer">Gempe et al., PLOS Biology (2009)</a>.</p></article></section>
 <footer><a href="#/una-femmina-senza-padre">← Esperimento precedente</a><p>Un locus, ereditarietà mendeliana, probabilità esatte. Nessuna mutazione casuale.</p></footer>
 </main>;
}



