import React from 'react';
export function InteractiveColony({population,selected,onToggle,onSelect}){
 return <section className="lab"><div className="lab-heading"><div><p className="eyebrow">1 / ELIMINAZIONE LARVALE</p><h2>Tre maschi diploidi, quattro linee familiari</h2></div></div><p className="scenario-result">Clicca direttamente uno dei tre riquadri arancioni «Maschio diploide» per eliminarlo. Clicca di nuovo sulla croce per ripristinarlo. Nei riquadri verdi in basso, «Vedi antenati» apre la genealogia del maschio sopravvissuto.</p><div className="graph-scroll" tabIndex="0" role="region" aria-label="Colonia interattiva"><svg width="1000" height="465" viewBox="0 0 1000 465" role="group" aria-label="Quattro linee familiari">
 <defs><marker id="population-arrow" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#98a487"/></marker></defs>
 {[0,1,2].map(g=><text key={g} x="12" y={73+g*145} className="generation">t{g}</text>)}
 {population.nodes.flatMap(n=>n.parents.filter(id=>population.nodes.some(p=>p.id===id)).map(id=>{const p=population.nodes.find(p=>p.id===id),active=n.status==='present';return <path key={id+n.id} d={`M${p.x} ${120+p.generation*145}L${n.x} ${24+n.generation*145}`} fill="none" stroke={active?'#98a487':'#d9d3c7'} strokeWidth="1.7" strokeDasharray={active?undefined:'4 5'} markerEnd={active?'url(#population-arrow)':undefined}/>;}))}
 {population.nodes.map(n=>{const removable=n.diploid,selectable=n.generation===2&&n.status==='present',button=removable||selectable,action=()=>removable?onToggle(n.id):onSelect(n.id),label=removable?`${n.status==='eliminated'?'Ripristina':'Elimina'} maschio diploide ${n.id}`:`Mostra antenati del maschio ${n.id}`,kind=n.diploid?'Maschio diploide':n.sex==='F'?'Femmina':'Maschio aploide';
 const content=<><span className="population-symbol">{n.status==='eliminated'?'×':n.status==='unborn'?'—':n.sex}</span><span>{kind}</span><small>{button&&`${n.id} · `}{n.status==='unborn'?'Non nasce':removable?(n.status==='eliminated'?'Ripristina':'Elimina'):selectable?'Vedi antenati':n.id}</small></>;
 return <foreignObject key={n.id} x={n.x-44} y={26+n.generation*145} width="88" height="94">{button?<button type="button" className={`population-card ${removable?'diploid':'survivor'} ${selected===n.id?'chosen':''}`} aria-label={label} aria-pressed={removable?n.status==='eliminated':selected===n.id} onClick={action}>{content}</button>:<div className={`population-card static ${n.status==='unborn'?'unborn':''}`} aria-label={`${n.id}: ${n.status==='unborn'?'non nasce':kind}`}>{content}</div>}</foreignObject>;})}

 </svg></div><p className="scenario-result" role="status">Popolazione rappresentata: <strong>{population.present}</strong> presenti · <strong>{population.eliminated}</strong> eliminati · <strong>{population.unborn}</strong> nascite impedite.</p><p className="scenario-result">× = eliminato da larva; — = non nasce. Frecce: genitore → figlio. I simboli indicano il tipo adulto.</p></section>;
}

