import React,{useEffect,useId,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {buildTree} from './model.js';
import './style.css';
import {Navigation} from './Navigation.jsx';
import UniparentalPage from './UniparentalPage.jsx';
import CsdPage from './CsdPage.jsx';
import SurvivalPage from './SurvivalPage.jsx';
function RuleInfo({number,title,children}) {
 const dialog=useRef(null), titleId=useId();
 return <><button className="info-button" aria-label={`Informazioni sulla regola ${number}`} aria-haspopup="dialog" onClick={()=>dialog.current.showModal()}><svg width="18" height="18" viewBox="0 0 20 20" fill="none" aria-hidden="true"><circle cx="10" cy="10" r="8" stroke="currentColor" strokeWidth="1.4"/><path d="M10 9v5" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round"/><circle cx="10" cy="6" r="1" fill="currentColor"/></svg></button><dialog className="rule-dialog" ref={dialog} aria-labelledby={titleId}><div className="dialog-heading"><p className="eyebrow">LA REGOLA {number} / APPROFONDIMENTO</p><button className="close-info" aria-label="Chiudi approfondimento" onClick={()=>dialog.current.close()}>×</button></div><h2 id={titleId}>{title}</h2><div className="dialog-copy">{children}</div><form method="dialog"><button className="understood">Ho capito</button></form></dialog></>;
}
function Bee({type,x=0,y=0}){return <g transform={`translate(${x} ${y})`}><circle r="16" fill={type==='F'?'#f7d888':'#dbe8e2'} stroke={type==='F'?'#bd8b31':'#658779'}/><ellipse cx="-4" cy="-4" rx="4" ry="6" fill="#fffdf6" transform="rotate(-28)"/><ellipse cx="4" cy="-4" rx="4" ry="6" fill="#fffdf6" transform="rotate(28)"/><ellipse cy="3" rx="5" ry="8" fill={type==='F'?'#956a22':'#456e5d'}/><path d="M-4 1H4M-4 5H4" stroke="#fff6d9" strokeWidth="1.5"/></g>}
function App(){const [depth,setDepth]=useState(6);const tree=useMemo(()=>buildTree(depth),[depth]);const count=tree.counts.at(-1);return <main>
<header><a href="#/" className="brand"><svg viewBox="-20 -20 40 40" width="34" height="34" aria-hidden="true"><Bee type="F"/></svg> API MATEMATICHE</a><Navigation page="fibonacci"/></header>
<section className="intro"><p className="eyebrow">PICCOLE API / GRANDI NUMERI</p><h1>Fibonacci, di madre<br/>in <em>madre.</em></h1><p>Parti da un fuco e risali il suo albero genealogico.<br className="desktop"/> Ogni generazione rivela il numero successivo della successione.</p></section>
<section className="rules" aria-label="Le regole del modello">
<article><span className="sex male">M</span><div className="rule-summary"><div className="rule-title"><strong>Un maschio, una madre.</strong><RuleInfo number={1} title="Come nasce un fuco?"><p>Nell’ape mellifera, il maschio è chiamato <strong>fuco</strong>. Normalmente nasce da un <strong>uovo non fecondato</strong>: lo sviluppo dell’embrione inizia senza che uno spermatozoo si unisca all’uovo. Questo processo si chiama <strong>partenogenesi arrenotoca</strong>.</p><p>La madre produce l’uovo attraverso la <strong>meiosi</strong>, che riduce a metà il numero di cromosomi. Il fuco è quindi <strong>aploide</strong>: possiede una sola serie di 16 cromosomi, ricevuta dalla madre. Le femmine sono invece normalmente diploidi, con due serie, per un totale di 32 cromosomi.</p><div className="info-example">Uovo materno non fecondato → fuco M<br/><span>Un solo genitore biologico: la madre F.</span></div><p>Il fuco non è una copia della madre: eredita una combinazione del suo patrimonio genetico. E non avere un padre non significa non avere un nonno: sua madre, nel nostro modello, ha a sua volta una madre e un padre.</p><p className="model-note"><strong>Nel modello:</strong> rappresentiamo tutti i nodi M come fuchi aploidi. In natura esistono anche maschi diploidi; questa eccezione è esclusa dalle nostre regole.</p><p className="info-source">Fonti: <a href="https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1000222" target="_blank" rel="noreferrer">Gempe et al., PLOS Biology (2009)</a>; <a href="https://www.nature.com/articles/nature05260" target="_blank" rel="noreferrer">Honeybee Genome Sequencing Consortium, Nature (2006)</a>.</p></RuleInfo></div><p>Ogni nodo M ha un solo genitore F.</p></div></article>
<article><span className="sex female">F</span><div className="rule-summary"><div className="rule-title"><strong>Una femmina, due genitori.</strong><RuleInfo number={2} title="Perché una femmina ha due genitori?"><p>Nel ciclo riproduttivo rappresentato, una femmina nasce da un <strong>uovo fecondato</strong>. Alla serie di cromosomi dell’uovo materno si aggiunge quella dello spermatozoo paterno: l’individuo è <strong>diploide</strong>, con 32 cromosomi.</p><p>Ogni figlia ha una madre e un solo padre biologico. Il fatto che una regina possa accoppiarsi con più fuchi non assegna più padri a una singola figlia.</p><div className="info-example">Uovo della madre F + spermatozoo del padre M<br/><span>Nel modello → figlia F, con due genitori distinti.</span></div><p className="model-note"><strong>Nel modello:</strong> ogni F nasce per riproduzione sessuata. Non includiamo la nascita di femmine senza fecondazione. Nelle api reali il sesso dipende anche dal gene <em>csd</em>: la fecondazione da sola non garantisce una femmina.</p><p>Nel grafo, ogni nodo F apre quindi due rami: uno verso F e uno verso M. Questa regola, insieme a quella dei maschi, genera la successione di Fibonacci.</p><p className="info-source">Fonte: <a href="https://journals.plos.org/plosbiology/article?id=10.1371/journal.pbio.1000222" target="_blank" rel="noreferrer">Gempe et al., PLOS Biology (2009)</a>.</p></RuleInfo></div><p>Ogni nodo F ha una madre F e un padre M.</p></div></article>
<article><span className="distinct">↗</span><div className="rule-summary"><div className="rule-title"><strong>Ogni ape è un individuo distinto.</strong><RuleInfo number={3} title="Perché i rami non si riuniscono?"><p>Questa è un’<strong>ipotesi matematica</strong>: ogni genitore aggiunto al grafo è un nuovo individuo. La stessa ape non compare mai come antenato lungo due percorsi diversi.</p><div className="info-example">Una posizione nell’albero = un individuo distinto.</div><p>In una genealogia reale, due rami possono risalire allo stesso antenato. In quel caso le posizioni nell’albero espanso e gli individui effettivi non sono più la stessa cosa: una persona o un’ape può occupare più posizioni genealogiche.</p><p>Per esempio, se due nodi M dello stesso livello avessero la stessa madre, i loro due rami arriverebbero a una sola F: due posizioni, ma un solo individuo. Qui le due madri sono sempre distinte.</p><p className="model-note"><strong>La garanzia:</strong> con questa ipotesi, le regole 1 e 2 e un maschio iniziale, i numeri di Fibonacci contano davvero gli <strong>individui</strong> di ogni generazione, non soltanto i percorsi: 1, 1, 2, 3, 5, 8…</p></RuleInfo></div><p>I rami non si riuniscono mai.</p></div></article>
</section>
<section className="lab"><div className="lab-heading"><div><p className="eyebrow">L’ALBERO DEGLI ANTENATI</p><h2>Una generazione alla volta</h2></div><div className="stepper" aria-label="Profondità del grafo"><button aria-label="Mostra una generazione in meno" disabled={depth===1} onClick={()=>setDepth(d=>d-1)}>−</button><span>Fino a <strong>g{depth}</strong></span><button aria-label="Mostra una generazione in più" disabled={depth===10} onClick={()=>setDepth(d=>d+1)}>+</button></div></div>
<div className="sequence" aria-label="Numero di individui per generazione">{tree.counts.map((n,g)=><div key={g} className={g===depth?'current':''}><span>g{g}</span><strong>{n}</strong></div>)}</div>
<div className="graph-meta"><p>Il presente in alto. Il passato verso il basso.</p><div className="legend"><span><i className="dot female"/>Femmina F</span><span><i className="dot male"/>Maschio M</span></div></div>
<div className="graph-scroll" tabIndex="0" role="region" aria-label="Albero completo, scorribile orizzontalmente"><svg className="tree" width={tree.width} height={tree.height} viewBox={`0 0 ${tree.width} ${tree.height}`} role="img" aria-label={`Albero genealogico del fuco: ${tree.counts.join(', ')} individui nelle generazioni da zero a ${depth}`}>
{tree.levels.map((level,g)=><g key={g}><line x1="115" x2={tree.width-15} y1={50+g*100} y2={50+g*100} stroke="#eeeade" strokeDasharray="3 6"/><text x="18" y={46+g*100} className="generation">g{g}</text><text x="18" y={65+g*100} className="row-count">{level.length} {level.length===1?'individuo':'individui'}</text></g>)}
{tree.nodes.flatMap(n=>n.parents.map(id=>{const p=tree.nodes[id];const y=50+n.generation*100;return <path key={`${n.id}-${id}`} d={`M${n.x} ${y+16} C${n.x} ${y+52},${p.x} ${y+48},${p.x} ${y+84}`} fill="none" stroke="#c6cdbd" strokeWidth="1.5"/>;}))}
{tree.nodes.map(n=><g key={n.id} className="bee-node"><title>{n.type==='M'?'Maschio':'Femmina'} · g{n.generation} · individuo {n.id+1}{n.generation===depth?' · limite della vista':''}</title><Bee type={n.type} x={n.x} y={50+n.generation*100}/><text x={n.x} y={79+n.generation*100} textAnchor="middle" className="node-label">{n.type}</text></g>)}
</svg></div><div className="graph-footer"><span>Tutte le api sono mostrate. Scorri lateralmente se l’albero supera lo schermo.</span><span>g0 è il fuco iniziale.</span></div></section>
<section className="explanation"><div><p className="eyebrow">NON È UNA COINCIDENZA</p><h2>Il numero nasce<br/>dalla regola.</h2><p>Ogni ape aggiunge una madre alla generazione precedente. Solo le femmine aggiungono anche un padre. Per questo, dopo i primi due livelli, ogni totale è la somma dei due precedenti.</p><p className="boundary">L’ultima riga è soltanto il limite della vista: anche quelle api hanno antenati.</p></div><div className="equation"><p>ALLA GENERAZIONE g{depth}</p>{depth>=2?<><div><span>{tree.counts[depth-2]}</span><i>+</i><span>{tree.counts[depth-1]}</span><i>=</i><strong>{count}</strong></div><small>g{depth-2} <span>+</span> g{depth-1} <span>→</span> g{depth}</small></>:<><div><strong>1</strong><i>→</i><strong>1</strong></div><small>Un fuco, una madre: i due valori iniziali.</small></>}<p className="formula">N(g) = N(g − 1) + N(g − 2), per g ≥ 2</p></div></section>
<footer><span>API MATEMATICHE</span><p>Un modello matematico ispirato alle api. Antenati sempre distinti, regole fisse, nessuna casualità.</p></footer></main>}
function Pages(){
 const [hash,setHash]=useState(window.location.hash);
 useEffect(()=>{const change=()=>{setHash(window.location.hash);window.scrollTo(0,0);};window.addEventListener('hashchange',change);return()=>window.removeEventListener('hashchange',change);},[]);
 const uniparental=hash==='#/una-femmina-senza-padre';
 const csd=hash==='#/alleli-e-sesso';
 const survival=hash==='#/genealogia-e-sopravvivenza';
 useEffect(()=>{document.title=survival?'Eliminazione larvale · Api matematiche':csd?'Alleli e sesso · Api matematiche':uniparental?'Una femmina senza padre · Api matematiche':'Api matematiche';},[uniparental,csd,survival]);
 return survival?<SurvivalPage/>:csd?<CsdPage/>:uniparental?<UniparentalPage/>:<App/>;
}
createRoot(document.getElementById('root')).render(<Pages/>);
